[project]
name = "panopticon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "chromadb>=0.4.22",
    "litellm>=1.30.3",
    "sqlalchemy>=2.0.27",
    "psycopg2-binary>=2.9.9",
]
